# Generated by Django 4.0.2 on 2022-04-30 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('one_To_one_app', '0002_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='course',
            new_name='Course',
        ),
    ]
